const cfg=window.EQUIPMENT_PAGE||{code:'AREA',name:'Equipment Area'};const key=`tanjung.equipment.${cfg.code}.v2`;
const prefix=(cfg.prefix||cfg.code.replace(/[^A-Z0-9]/gi,'')).slice(0,4).toUpperCase();
const defaults={pumps:[{tag:`P-${prefix}-01A`,type:'Centrifugal Pump',model:'Process Duty',design:'10,000 BPD',head:'145 m',power:'110 kW',material:'CS / SS316 Trim',status:'RUNNING'},{tag:`P-${prefix}-01B`,type:'Centrifugal Pump',model:'Standby Duty',design:'10,000 BPD',head:'145 m',power:'110 kW',material:'CS / SS316 Trim',status:'STANDBY'}],vessels:[{tag:`V-${prefix}-01`,type:'Separator / Vessel',model:'Horizontal 3-Phase',design:'2,000 BBL',pressure:'150 psig',limit:'75%',level:'65%',status:'RUNNING'},{tag:`T-${prefix}-01`,type:'Storage Tank',model:'Atmospheric',design:'10,000 BBL',pressure:'ATM',limit:'80%',level:'45%',status:'RUNNING'}]};
let db=load();let edit={type:null,index:null};
function load(){try{return JSON.parse(localStorage.getItem(key))||structuredClone(defaults)}catch(e){return structuredClone(defaults)}}function save(){localStorage.setItem(key,JSON.stringify(db));render()}
function badge(s){const c=s==='RUNNING'?'badge-run':s==='STANDBY'?'badge-standby':'badge-repair';return `<span class="badge ${c}">${s}</span>`}
function render(){document.getElementById('pageTitle').textContent=cfg.name;document.title=`${cfg.name} - Equipment Database`;document.getElementById('areaCode').textContent=cfg.code;document.getElementById('pumpCount').textContent=db.pumps.length;document.getElementById('vesselCount').textContent=db.vessels.length;document.getElementById('runningCount').textContent=[...db.pumps,...db.vessels].filter(x=>x.status==='RUNNING').length;document.getElementById('standbyCount').textContent=[...db.pumps,...db.vessels].filter(x=>x.status==='STANDBY').length;document.getElementById('pumpBody').innerHTML=db.pumps.map((r,i)=>`<tr><td class="tag">${r.tag}</td><td>${r.type}</td><td>${r.model}</td><td>${r.design}</td><td>${r.head}</td><td>${r.power}</td><td>${r.material}</td><td>${badge(r.status)}</td><td class="actions"><button class="btn btn-warning" onclick="openModal('pumps',${i})">Edit</button><button class="btn btn-danger" onclick="removeRow('pumps',${i})">Del</button></td></tr>`).join('')||'<tr><td class="empty" colspan="9">Belum ada data pompa.</td></tr>';document.getElementById('vesselBody').innerHTML=db.vessels.map((r,i)=>`<tr><td class="tag">${r.tag}</td><td>${r.type}</td><td>${r.model}</td><td>${r.design}</td><td>${r.pressure}</td><td>${r.limit}</td><td>${r.level}</td><td>${badge(r.status)}</td><td class="actions"><button class="btn btn-warning" onclick="openModal('vessels',${i})">Edit</button><button class="btn btn-danger" onclick="removeRow('vessels',${i})">Del</button></td></tr>`).join('')||'<tr><td class="empty" colspan="9">Belum ada data tank / vessel.</td></tr>'}
function openModal(type,index=null){edit={type,index};const isPump=type==='pumps';document.getElementById('modalTitle').textContent=index===null?`Tambah ${isPump?'Pump':'Tank / Vessel'}`:`Edit ${isPump?'Pump':'Tank / Vessel'}`;document.getElementById('fieldHeadLabel').textContent=isPump?'Rated Head':'Design Pressure';document.getElementById('fieldPowerLabel').textContent=isPump?'Motor Power':'Operating Limit';document.getElementById('fieldMaterialLabel').textContent=isPump?'Material':'Current Level';const row=index===null?{}:db[type][index];['tag','type','model','design','status'].forEach(f=>document.getElementById(`f-${f}`).value=row[f]|| (f==='status'?'RUNNING':'') );document.getElementById('f-head').value=row[isPump?'head':'pressure']||'';document.getElementById('f-power').value=row[isPump?'power':'limit']||'';document.getElementById('f-material').value=row[isPump?'material':'level']||'';document.getElementById('crudModal').classList.add('open')}
function closeModal(){document.getElementById('crudModal').classList.remove('open')}
function submitForm(){const type=edit.type;if(!type)return;const isPump=type==='pumps';const row={tag:document.getElementById('f-tag').value.trim(),type:document.getElementById('f-type').value.trim(),model:document.getElementById('f-model').value.trim(),design:document.getElementById('f-design').value.trim(),status:document.getElementById('f-status').value};if(!row.tag){alert('Tag ID wajib diisi.');return}if(isPump){row.head=document.getElementById('f-head').value.trim();row.power=document.getElementById('f-power').value.trim();row.material=document.getElementById('f-material').value.trim()}else{row.pressure=document.getElementById('f-head').value.trim();row.limit=document.getElementById('f-power').value.trim();row.level=document.getElementById('f-material').value.trim()}if(edit.index===null)db[type].push(row);else db[type][edit.index]=row;save();closeModal()}
function removeRow(type,index){if(confirm(`Hapus ${db[type][index].tag} dari database equipment?`)){db[type].splice(index,1);save()}}
function resetDb(){if(confirm('Kembalikan master equipment halaman ini ke data contoh awal?')){db=structuredClone(defaults);save()}}
window.openModal=openModal;window.closeModal=closeModal;window.submitForm=submitForm;window.removeRow=removeRow;window.resetDb=resetDb;render();document.getElementById('crudModal').addEventListener('click',e=>{if(e.target.id==='crudModal')closeModal()});
